services:
  pg-itp-micro-db:
    image: postgres:17.5-bullseye
    container_name: pg-itp-micro-db
    environment:
      POSTGRES_USER: itpusr
      POSTGRES_PASSWORD: itp@168
    ports:
      - "16168:5432"
    volumes:
      - ./init_scripts/pg_itp_micro_init.sql:/docker-entrypoint-initdb.d/pg_itp_micro_init.sql
      - pg-itp-micro-vol:/var/lib/postgresql/data
    networks:
      - itp-net

  pg-itp-iam-db:
    image: postgres:17.5-bullseye
    container_name: pg-itp-iam-db
    environment:
      POSTGRES_USER: c
      POSTGRES_PASSWORD: itp@168
    ports:
      - "16850:5432"
    volumes:
      - ./init_scripts/pg_itp_iam_init.sql:/docker-entrypoint-initdb.d/pg_itp_iam_init.sql
      - pg-itp-iam-vol:/var/lib/postgresql/data
    networks:
      - itp-net

volumes:
  pg-itp-iam-vol:
  pg-itp-micro-vol:

networks:
  itp-net:
    external: true
