spring:
  application:
    name: customer
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  http://localhost:9090
  datasource:
    driver-class-name: org.postgresql.Driver
    username: itpusr
    password: itp@168
    url: jdbc:postgresql://localhost:16168/db_customer
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
axon:
  axonserver:
    enabled: false
  serializer:
    general: jackson3
    events: jackson3
    messages: jackson3
server:
  port: 20260
  # Strategy JPA