spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  data:
    redis:
      host: localhost
      port: 6379
      password: qwer
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 5s

          routes:
            - id: pipeline
              uri: lb://pipeline
              predicates:
                - Path=/pipeline/**
              filters:
                - RewritePath=/pipeline/(?<segment>.*),/$\{segment}
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    redis-rate-limiter.requestedTokens: 1
#                - name: Retry
#                  args:
#                    retries: 3
#                    statuses: BAD_GATEWAY
#                    methods: GET,POST
#                    backoff:
#                      firstBackoff: 10ms
#                      maxBackoff: 50ms
#                      factor: 2
#                      basedOnPreviousValue: false
#                - name: CircuitBreaker
#                  args:
#                    name: pipelineCircuitBreaker
#                    fallbackUri: forward:/fallback/pipeline/client/account/secured
#                    statusCodes:
#                      - 500
            - id: account
              uri: lb://account
              predicates:
                - Path=/account/**
              filters:
                - RewritePath=/account/(?<segment>.*),/$\{segment}
                - name: CircuitBreaker
                  args:
                    name: accountCircuitBreaker

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
      client:
        provider:
          itp-standard:
            issuer-uri: http://localhost:9090
        registration:
          itp-standard:
            provider: itp-standard
            client-id: itp-standard
            client-secret: qwerqwer
            redirect-uri: http://localhost:9999/login/oauth2/code/itp-standard
            authorization-grant-type:
              - authorization_code
              - client_credentials
              - refresh_token
            scope:
              - openid
              - email
              - profile
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50 # Percentage
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state: 10000
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9999
